export enum Namespaces {
    "rdf" = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "im" = "http://endhealth.info/im#",
    "imq" = "http://endhealth.info/imq#",
    "bc" = "http://endhealth.info/bc#",
    "rdfs" = "http://www.w3.org/2000/01/rdf-schema#",
    "emis" = "http://endhealth.info/emis#",
    "sn" = "http://snomed.info/sct#",
    "ods" = "http://endhealth.info/ods#",
    "owl" = "http://www.w3.org/2002/07/owl#",
    "prov" = "http://www.w3.org/ns/prov#",
    "tpp" = "http://endhealth.info/tpp#",
    "xml" = "http://www.w3.org/XML/1998/namespace#",
    "sh" = "http://www.w3.org/ns/shacl#",
    "opcs4" = "http://endhealth.info/opcs4#",
    "vis" = "http://endhealth.info/vision#",
    "orole" = "https://directory.spineservices.nhs.uk/STU3/CodeSystem/ODSAPI-OrganizationRole-1#",
    "xsd" = "http://www.w3.org/2001/XMLSchema#",
}